config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'high_voltage/pages#show', id: 'about'
  namespace :admin do
    resources :users do
      collection do
        post 'destroy_all', to: 'users#destroy_all', as: :destroy_all
      end
      member do
        get 'resend_confirmation_instructions', to: 'users#resend_confirmation_instructions',
                                                as: :resend_confirmation_instructions
      end
    end
  end
  devise_for :users, skip: [:registrations], controllers: { confirmations: 'confirmations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :cases, except: %i[destroy] do
    resources :search_nannies, only: :index
    put 'reject', to: 'cases/states#reject', as: :reject
    put 'discard', to: 'cases/states#discard', as: :discard
    put 'request_nanny/:user_id', to: 'cases/states#request_nanny', as: :request_nanny
    get 'show_nanny/:id', to: 'users#show', as: :show_nanny
    put 'accept', to: 'cases/states#accept', as: :accept
    put 'refuse', to: 'cases/states#refuse', as: :refuse
    put 'finish', to: 'cases/states#finish', as: :finish
    put 'complete', to: 'cases/states#complete', as: :complete
    put 'reset', to: 'cases/states#reset', as: :reset
    get 'pdf', to: 'cases/pdf#pdf', as: :pdf
    collection do
      get 'csv', to: 'cases#csv_export', as: :csv
    end
  end

  resources :users, except: %i[new create]
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  language               :string
#  language_other         :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  name                   :string
#  nda                    :boolean
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  extend Enumerize
  include Languagable

  attr_accessor :strict_validation, :other_language

  has_many :care_ages_users, dependent: :delete_all
  has_many :care_ages, through: :care_ages_users
  has_one :address, as: :addressable, dependent: :destroy
  has_one :bank_account, dependent: :destroy
  has_one :user_info, dependent: :destroy
  has_many :cases, dependent: :restrict_with_error
  has_many :help_service_assignments, as: :assignee, dependent: :destroy
  has_many :help_services, through: :help_service_assignments
  has_many :refusals, dependent: :destroy
  has_many :refused_cases, through: :refusals, source: :case

  before_validation :set_name_from_address

  accepts_nested_attributes_for :address, :bank_account, :user_info, :help_service_assignments, :care_ages_users

  validates :address, :bank_account, presence: true
  validates :care_ages, :help_services,
            presence: true,
            if: ->(u) { u.strict_validation }

  enumerize :role, in: %i[nanny admin], default: :nanny,
                   predicates: true, scope: true

  devise :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :validatable,
         :trackable

  reverse_geocoded_by 'locations.latitude', 'locations.longitude'

  scope :nearby_nannies_by_coordinates, lambda { |coordinates = []|
    joins(address: :location).with_role(:nanny).near(coordinates, 1000, units: :km)
  }
  scope :without_refusals, lambda { |case_id|
    where.not(id: Refusal.where(case_id: case_id).map(&:user_id))
  }

  delegate :first_name, to: :address, prefix: true, allow_nil: true
  delegate :full_name, to: :address, allow_nil: true
  delegate :last_name, to: :address, prefix: true, allow_nil: true
  delegate :street, to: :address, prefix: true, allow_nil: true
  delegate :city, to: :address, prefix: true, allow_nil: true
  delegate :zip, to: :address, prefix: true, allow_nil: true
  delegate :full_address, to: :address, allow_nil: true
  delegate :location_address, to: :address, allow_nil: true
  delegate :salutation, to: :address, allow_nil: true
  delegate :bic, to: :bank_account, prefix: true, allow_nil: true
  delegate :iban, to: :bank_account, prefix: true, allow_nil: true
  delegate :account_holder, to: :bank_account, prefix: true, allow_nil: true
  delegate :reference_to_diabetes, to: :user_info, allow_nil: true
  delegate :phone_mobile, to: :address, allow_nil: true
  delegate :phone_private, to: :address, allow_nil: true
  delegate :phone_business, to: :address, allow_nil: true
  delegate :email_business, to: :address, allow_nil: true
  delegate :birthday, to: :user_info, allow_nil: true
  delegate :occupation, to: :user_info, allow_nil: true

  protected

    def set_name_from_address
      self.name = address&.full_name
    end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < ApplicationController
    after_action :verify_authorized

    before_action :set_user, except: %i[index new create destroy_all]

    def index
      @users_grid = initialize_grid(
        policy_scope(User), include: %i[address], name: 'users',
                            enable_export_to_csv: true, csv_file_name: 'users', csv_field_separator: ';',
                            order: 'users.id', order_direction: 'desc',
                            custom_order: {
                              'users.language' => 'lower(users.language)',
                              'users.email' => 'lower(users.email)',
                              'addresses.last_name' => 'lower(addresses.last_name)',
                              'addresses.first_name' => 'lower(addresses.first_name)'
                            }
      )
      export_grid_if_requested('users' => 'users_grid')
      authorize User
    end

    def new
      @form = UserCreationForm.new
      @nr = SecureRandom.alphanumeric
      @form.prebuild_care_ages
      @form.prebuild_help_service_assignments
      authorize User
    end

    def create
      @form = UserCreationForm.new(create_user_params)
      if @form.save
        redirect_to admin_users_path, notice: 'Benutzer wurde erfolgreich erstellt'
      else
        render :new, alert: 'Benutzer kann nicht erstellt werden'
      end
      authorize User
    end

    def show; end

    def edit
      @care_ages_users = CareAge.all.map do |care_age|
        CareAgesUser.find_or_initialize_by(care_age: care_age, user: @user)
      end
      @help_service_assignments = HelpService.where('key != ?', :used_on_fairs).map do |help_service|
        HelpServiceAssignment.find_or_initialize_by(help_service: help_service, assignee: @user)
      end
    end

    def update
      clear_if_valid(@user, update_user_params)
      if @user.update(update_user_params)
        redirect_to edit_admin_user_path(@user), notice: I18n.t('admin.update.update_success')
      else
        redirect_to edit_admin_user_path(@user), alert: I18n.t('admin.update.update_error')
      end
    end

    def destroy_all
      authorize User

      return if params&.dig(:users, :selected).nil?

      User.where(id: params[:users][:selected]).destroy_all
      redirect_to admin_users_path, notice: 'Die Benutzer wurden gelöscht.'
    end

    def destroy
      authorize @user
      if @user.destroy
        redirect_to(admin_users_path, notice: 'Der Benutzer wurde gelöscht.')
      else
        redirect_to admin_user_path(@user), alert: 'Der Benutzer kann nicht gelöscht werden.'
      end
    end

    def resend_confirmation_instructions
      @user.send_confirmation_instructions
      @user.update(confirmed_at: nil)
      redirect_to(admin_users_path, notice: 'Die Einladung wurde erneut versendet.')
    end

    private

      def clear_if_valid(user, params)
        user.assign_attributes(params)
        return if user.invalid?

        user.skip_reconfirmation!
        user.care_ages_users.clear
        user.help_service_assignments.clear
      end

      def set_user
        @user = User.find(params[:id])
        authorize @user
      end

      def create_user_params
        params.require(:user).permit(
          :address_salutation, :address_first_name, :address_last_name, :address_phone_business, :address_phone_private,
          :address_street, :address_zip, :address_city, :address_email_business, :address_phone_mobile,
          :user_email, :user_role, :user_password, :user_password_confirmation, :user_language, :user_language_other,
          :user_info_birthday, :user_info_occupation, :care_ages, :help_services,
          :bank_account_account_holder, :bank_account_iban, :bank_account_bic,
          user_info_reference_to_diabetes: [],
          help_service_assignments_attributes: %i[help_service_id assignee_type assignee_id],
          care_ages_users_attributes: %i[care_age_id user_id]
        )
      end

      def update_user_params
        parameters = params.require(:user).permit(
          :email, :role, :password, :password_confirmation, :language, :language_other,
          user_info_attributes: [:id, :birthday, :occupation, reference_to_diabetes: []],
          address_attributes: %i[id street zip city phone_private phone_mobile phone_business email_business
                                 salutation first_name last_name ],
          bank_account_attributes: %i[id account_holder iban bic],
          care_ages_users_attributes: %i[_delete care_age_id user_id],
          help_service_assignments_attributes: %i[help_service_id assignee_type assignee_id]
        )
        parameters[:care_ages_users_attributes]&.reject! { |_k, v| v['user_id'] == '0' }
        parameters[:help_service_assignments_attributes]&.reject! { |_k, v| v['assignee_id'] == '0' }
        parameters
      end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  after_action :verify_authorized

  before_action :set_user, except: [:index]

  def index
    @users = User.all
    authorize User
  end

  def edit
    @user.bank_account ||= @user.build_bank_account
  end

  def update
    delete_password_if_blank

    if @user.update(user_params.merge(strict_validation: true))
      redirect_to edit_user_path(@user), notice: t('.update_success')
    else
      flash.now[:alert] = t('.update_error')
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_session_path, notice: t('devise.registrations.destroyed')
  end

  private

    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    def user_params
      params.require(:user).permit(
        :email, :language_other, :password, :password_confirmation,
        address_attributes: %i[salutation first_name last_name street zip city phone_private
                               phone_mobile phone_business email_business],
        bank_account_attributes: %i[account_holder iban bic],
        language: [],
        care_age_ids: [],
        help_service_ids: [],
        user_info_attributes: [:birthday, :occupation, reference_to_diabetes: []]
      )
    end

    def delete_password_if_blank
      return if params[:user][:password].present?

      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def reference_to_diabetes_list
    UserInfo.reference_to_diabetes.options
  end

  def self.roles
    User.role.values.map { |r| [r&.capitalize, r] }
  end

  def all_languages
    Child.language.values.map { |r| [r&.text, r] }
  end

  def reference_to_diabetes_text(reference_to_diabetes)
    return if reference_to_diabetes.blank?

    reference_to_diabetes.texts.join(', ')
  end

  def show_complete_profile_flash?(user)
    user&.nanny? &&
      !user&.valid? &&
      controller_name == 'pages'
  end
end

app/views/users/_form.slim
= simple_form_for(user, defaults: { input_html: { class: 'form-inline' } }) do |f|
  h3 = t('.address_title')
  hr.mb-4
  = f.simple_fields_for :address do |a|
    = a.input :salutation, placeholder: t('activerecord.attributes.address.salutation')
    = a.input :first_name, placeholder: t('activerecord.attributes.address.first_name')
    = a.input :last_name, placeholder: t('activerecord.attributes.address.last_name')
    = a.input :street, placeholder: t('activerecord.attributes.address.street')
    = a.input :zip, placeholder: t('activerecord.attributes.address.zip')
    = a.input :city, placeholder: t('activerecord.attributes.address.city')
  h3 = t('.data_title')
  hr.mb-4
  = f.input :other_language, as: :boolean
  .other_language
    = f.input :language, label: false, collection: user_languages_list
  = f.input :language_other
  = f.simple_fields_for :user_info do |ui|
    = ui.input :birthday, as: :string, placeholder: t('activerecord.attributes.user_info.birthday'),
               input_html: { 'data-provide': 'datepicker',
                             'data-date-format': 'dd.mm.yyyy',
                             'data-date-language': 'de',
                             'data-date-autoclose': true,
                             value: l(ui.object.birthday) }
    = ui.input :occupation, placeholder: t('activerecord.attributes.user_info.occupation')
    = ui.input :reference_to_diabetes, as: :check_boxes, collection: reference_to_diabetes_list,
            label: t('activerecord.attributes.user_info.reference_to_diabetes')
  = f.association :care_ages, as: :check_boxes, label_method: :description
  = f.association :help_services, as: :check_boxes, label_method: :description, value_method: :id,
          label: t('activerecord.attributes.user.help_service_assignments')
  h3 = t('.contact_title')
  hr.mb-4
  = f.simple_fields_for :address do |ua|
    = ua.input :phone_private, label: t('activerecord.attributes.address.phone_private')
    = ua.input :phone_mobile, label: t('activerecord.attributes.address.phone_mobile')
    = ua.input :phone_business, label: t('activerecord.attributes.address.phone_business')
    = ua.input :email_business, label: t('activerecord.attributes.address.email_business')
  h3 = t('.bank_title')
  hr.mb-4
  = f.simple_fields_for :bank_account do |ba|
    = ba.input :account_holder, placeholder: t('activerecord.attributes.bank_account.account_holder')
    = ba.input :iban, placeholder: t('activerecord.attributes.bank_account.iban')
    = ba.input :bic, placeholder: t('activerecord.attributes.bank_account.bic')
  h3 = t('.profile_title')
  hr.mb-4
  = f.input :email, as: :email, placeholder: t('activerecord.attributes.user.email'), required: true
  = f.input :password, as: :password, placeholder: t('activerecord.attributes.user.password'),
          required: true
  = f.input :password_confirmation, as: :password, required: true,
          placeholder: t('activerecord.attributes.user.password_confirmation')
  hr.mb-4
    = f.submit t('.save'), class: 'btn btn-primary btn-lg mb-4'
    = link_to t('.delete'), user, method: :delete, data: { confirm: t('.confirm_delete') },
            class: 'btn btn-danger btn-lg mb-4', style: 'float:right;'

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= simple_form_for(user, html: { class: 'form-inline' }) do |f| %>
    <%= f.select(:role, UsersHelper.roles) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/edit.html.slim
= render 'form', user: @user

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <%= render user %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.slim
.container
  .row
    .col-sm-12
      .card.mb-2
        .card-body
          h3.card-title = t('.nanny_info')
          p.card-text
            table.table.table-head-noborder
              tbody
                tr
                  td style="width: 30rem" = t('.salutation')
                  td = @user.salutation
                tr
                  td = t('.name')
                  td = @user.full_name
                tr
                  td = t('.address')
                  td = simple_format(@user.full_address)
                tr
                  td = t('.email')
                  td = @user.email
                tr
                  td = t('.language')
                  td = @user.languages
                tr
                  td = t('.user_info.birthday')
                  td = l(@user.user_info&.birthday)
                tr
                  td = t('.language')
                  td = @user.languages
                tr
                  td = t('.user_info.occupation')
                  td = @user.user_info&.occupation
                tr
                  td = t('.user_info.reference_to_diabetes')
                  td = reference_to_diabetes_text(@user.reference_to_diabetes)
                tr
                  td = t('.care_ages')
                  td
                    ul
                      - @user.care_ages.each do |u|
                        li = u.description
                tr
                  td = t('.help_services')
                  td
                    ul
                      - @user.help_services.each do |u|
                        li = u.description
                tr
                  td = t('.phone_private')
                  td = @user.phone_private
                tr
                  td = t('.phone_mobile')
                  td = @user.phone_mobile
                tr
                  td = t('.phone_business')
                  td = @user.phone_business
                tr
                  td = t('.email_business')
                  td = @user.email_business

  - if params[:case_id].present?
    .row
      .col-sm-12
        .card.mb-4
          .card-body
            = link_to t('.inquire'), case_request_nanny_path(case_id: params[:case_id], user_id: @user.id),
                    method: :put, class: 'btn btn-primary'
            = link_to t('.back'), :back, class: 'btn btn-secondary'