config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'high_voltage/pages#show', id: 'about'
  namespace :admin do
    resources :users do
      collection do
        post 'destroy_all', to: 'users#destroy_all', as: :destroy_all
      end
      member do
        get 'resend_confirmation_instructions', to: 'users#resend_confirmation_instructions',
                                                as: :resend_confirmation_instructions
      end
    end
  end
  devise_for :users, skip: [:registrations], controllers: { confirmations: 'confirmations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :cases, except: %i[destroy] do
    resources :search_nannies, only: :index
    put 'reject', to: 'cases/states#reject', as: :reject
    put 'discard', to: 'cases/states#discard', as: :discard
    put 'request_nanny/:user_id', to: 'cases/states#request_nanny', as: :request_nanny
    get 'show_nanny/:id', to: 'users#show', as: :show_nanny
    put 'accept', to: 'cases/states#accept', as: :accept
    put 'refuse', to: 'cases/states#refuse', as: :refuse
    put 'finish', to: 'cases/states#finish', as: :finish
    put 'complete', to: 'cases/states#complete', as: :complete
    put 'reset', to: 'cases/states#reset', as: :reset
    get 'pdf', to: 'cases/pdf#pdf', as: :pdf
    collection do
      get 'csv', to: 'cases#csv_export', as: :csv
    end
  end

  resources :users, except: %i[new create]
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  language               :string
#  language_other         :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  name                   :string
#  nda                    :boolean
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  extend Enumerize
  include Languagable

  attr_accessor :strict_validation, :other_language

  has_many :care_ages_users, dependent: :delete_all
  has_many :care_ages, through: :care_ages_users
  has_one :address, as: :addressable, dependent: :destroy
  has_one :bank_account, dependent: :destroy
  has_one :user_info, dependent: :destroy
  has_many :cases, dependent: :restrict_with_error
  has_many :help_service_assignments, as: :assignee, dependent: :destroy
  has_many :help_services, through: :help_service_assignments
  has_many :refusals, dependent: :destroy
  has_many :refused_cases, through: :refusals, source: :case

  before_validation :set_name_from_address

  accepts_nested_attributes_for :address, :bank_account, :user_info, :help_service_assignments, :care_ages_users

  validates :address, :bank_account, presence: true
  validates :care_ages, :help_services,
            presence: true,
            if: ->(u) { u.strict_validation }

  enumerize :role, in: %i[nanny admin], default: :nanny,
                   predicates: true, scope: true

  devise :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :validatable,
         :trackable

  reverse_geocoded_by 'locations.latitude', 'locations.longitude'

  scope :nearby_nannies_by_coordinates, lambda { |coordinates = []|
    joins(address: :location).with_role(:nanny).near(coordinates, 1000, units: :km)
  }
  scope :without_refusals, lambda { |case_id|
    where.not(id: Refusal.where(case_id: case_id).map(&:user_id))
  }

  delegate :first_name, to: :address, prefix: true, allow_nil: true
  delegate :full_name, to: :address, allow_nil: true
  delegate :last_name, to: :address, prefix: true, allow_nil: true
  delegate :street, to: :address, prefix: true, allow_nil: true
  delegate :city, to: :address, prefix: true, allow_nil: true
  delegate :zip, to: :address, prefix: true, allow_nil: true
  delegate :full_address, to: :address, allow_nil: true
  delegate :location_address, to: :address, allow_nil: true
  delegate :salutation, to: :address, allow_nil: true
  delegate :bic, to: :bank_account, prefix: true, allow_nil: true
  delegate :iban, to: :bank_account, prefix: true, allow_nil: true
  delegate :account_holder, to: :bank_account, prefix: true, allow_nil: true
  delegate :reference_to_diabetes, to: :user_info, allow_nil: true
  delegate :phone_mobile, to: :address, allow_nil: true
  delegate :phone_private, to: :address, allow_nil: true
  delegate :phone_business, to: :address, allow_nil: true
  delegate :email_business, to: :address, allow_nil: true
  delegate :birthday, to: :user_info, allow_nil: true
  delegate :occupation, to: :user_info, allow_nil: true

  protected

    def set_name_from_address
      self.name = address&.full_name
    end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < ApplicationController
    after_action :verify_authorized

    before_action :set_user, except: %i[index new create destroy_all]

    def index
      @users_grid = initialize_grid(
        policy_scope(User), include: %i[address], name: 'users',
                            enable_export_to_csv: true, csv_file_name: 'users', csv_field_separator: ';',
                            order: 'users.id', order_direction: 'desc',
                            custom_order: {
                              'users.language' => 'lower(users.language)',
                              'users.email' => 'lower(users.email)',
                              'addresses.last_name' => 'lower(addresses.last_name)',
                              'addresses.first_name' => 'lower(addresses.first_name)'
                            }
      )
      export_grid_if_requested('users' => 'users_grid')
      authorize User
    end

    def new
      @form = UserCreationForm.new
      @nr = SecureRandom.alphanumeric
      @form.prebuild_care_ages
      @form.prebuild_help_service_assignments
      authorize User
    end

    def create
      @form = UserCreationForm.new(create_user_params)
      if @form.save
        redirect_to admin_users_path, notice: 'Benutzer wurde erfolgreich erstellt'
      else
        render :new, alert: 'Benutzer kann nicht erstellt werden'
      end
      authorize User
    end

    def show; end

    def edit
      @care_ages_users = CareAge.all.map do |care_age|
        CareAgesUser.find_or_initialize_by(care_age: care_age, user: @user)
      end
      @help_service_assignments = HelpService.where('key != ?', :used_on_fairs).map do |help_service|
        HelpServiceAssignment.find_or_initialize_by(help_service: help_service, assignee: @user)
      end
    end

    def update
      clear_if_valid(@user, update_user_params)
      if @user.update(update_user_params)
        redirect_to edit_admin_user_path(@user), notice: I18n.t('admin.update.update_success')
      else
        redirect_to edit_admin_user_path(@user), alert: I18n.t('admin.update.update_error')
      end
    end

    def destroy_all
      authorize User

      return if params&.dig(:users, :selected).nil?

      User.where(id: params[:users][:selected]).destroy_all
      redirect_to admin_users_path, notice: 'Die Benutzer wurden gelöscht.'
    end

    def destroy
      authorize @user
      if @user.destroy
        redirect_to(admin_users_path, notice: 'Der Benutzer wurde gelöscht.')
      else
        redirect_to admin_user_path(@user), alert: 'Der Benutzer kann nicht gelöscht werden.'
      end
    end

    def resend_confirmation_instructions
      @user.send_confirmation_instructions
      @user.update(confirmed_at: nil)
      redirect_to(admin_users_path, notice: 'Die Einladung wurde erneut versendet.')
    end

    private

      def clear_if_valid(user, params)
        user.assign_attributes(params)
        return if user.invalid?

        user.skip_reconfirmation!
        user.care_ages_users.clear
        user.help_service_assignments.clear
      end

      def set_user
        @user = User.find(params[:id])
        authorize @user
      end

      def create_user_params
        params.require(:user).permit(
          :address_salutation, :address_first_name, :address_last_name, :address_phone_business, :address_phone_private,
          :address_street, :address_zip, :address_city, :address_email_business, :address_phone_mobile,
          :user_email, :user_role, :user_password, :user_password_confirmation, :user_language, :user_language_other,
          :user_info_birthday, :user_info_occupation, :care_ages, :help_services,
          :bank_account_account_holder, :bank_account_iban, :bank_account_bic,
          user_info_reference_to_diabetes: [],
          help_service_assignments_attributes: %i[help_service_id assignee_type assignee_id],
          care_ages_users_attributes: %i[care_age_id user_id]
        )
      end

      def update_user_params
        parameters = params.require(:user).permit(
          :email, :role, :password, :password_confirmation, :language, :language_other,
          user_info_attributes: [:id, :birthday, :occupation, reference_to_diabetes: []],
          address_attributes: %i[id street zip city phone_private phone_mobile phone_business email_business
                                 salutation first_name last_name ],
          bank_account_attributes: %i[id account_holder iban bic],
          care_ages_users_attributes: %i[_delete care_age_id user_id],
          help_service_assignments_attributes: %i[help_service_id assignee_type assignee_id]
        )
        parameters[:care_ages_users_attributes]&.reject! { |_k, v| v['user_id'] == '0' }
        parameters[:help_service_assignments_attributes]&.reject! { |_k, v| v['assignee_id'] == '0' }
        parameters
      end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  after_action :verify_authorized

  before_action :set_user, except: [:index]

  def index
    @users = User.all
    authorize User
  end

  def edit
    @user.bank_account ||= @user.build_bank_account
  end

  def update
    delete_password_if_blank

    if @user.update(user_params.merge(strict_validation: true))
      redirect_to edit_user_path(@user), notice: t('.update_success')
    else
      flash.now[:alert] = t('.update_error')
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_session_path, notice: t('devise.registrations.destroyed')
  end

  private

    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    def user_params
      params.require(:user).permit(
        :email, :language_other, :password, :password_confirmation,
        address_attributes: %i[salutation first_name last_name street zip city phone_private
                               phone_mobile phone_business email_business],
        bank_account_attributes: %i[account_holder iban bic],
        language: [],
        care_age_ids: [],
        help_service_ids: [],
        user_info_attributes: [:birthday, :occupation, reference_to_diabetes: []]
      )
    end

    def delete_password_if_blank
      return if params[:user][:password].present?

      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def reference_to_diabetes_list
    UserInfo.reference_to_diabetes.options
  end

  def self.roles
    User.role.values.map { |r| [r&.capitalize, r] }
  end

  def all_languages
    Child.language.values.map { |r| [r&.text, r] }
  end

  def reference_to_diabetes_text(reference_to_diabetes)
    return if reference_to_diabetes.blank?

    reference_to_diabetes.texts.join(', ')
  end

  def show_complete_profile_flash?(user)
    user&.nanny? &&
      !user&.valid? &&
      controller_name == 'pages'
  end
end

app/views/admin/users/_edit.slim
= simple_form_for(@user, url: admin_user_path, method: :patch,
        defaults: { input_html: { class: 'form-inline' } }) do |f|
  h3 = 'Adresse-Informationen'
  hr.mb-4
    = f.fields_for :address do |a|
      = a.input :salutation, placeholder: t('activerecord.attributes.address.salutation'),
              label: t('activerecord.attributes.address.salutation'), required: true
      = a.input :first_name, placeholder: t('activerecord.attributes.address.first_name'),
              label: t('activerecord.attributes.address.first_name')
      = a.input :last_name, placeholder: t('activerecord.attributes.address.last_name'),
              label: t('activerecord.attributes.address.last_name')
      = a.input :street, placeholder: t('activerecord.attributes.address.street'),
              label: t('activerecord.attributes.address.street')
      = a.input :zip, placeholder: t('activerecord.attributes.address.zip'),
              label: t('activerecord.attributes.address.zip')
      = a.input :city, placeholder: t('activerecord.attributes.address.city'),
              label: t('activerecord.attributes.address.city')
    h3 = 'Benutzer-Informationen'
  hr.mb-4
    = f.input :email, as: :email, placeholder: t('activerecord.attributes.user.email'),
            label: t('activerecord.attributes.user.email'), required: true
    = f.input :role, collection: UsersHelper.roles,
            label: t('activerecord.attributes.user.role'), input_html: { class: 'custom-select' }
  .other_language
  = f.input :language, label: false, collection: all_languages,
          input_html: { class: 'custom-select', value: f.object.language.values }
  = f.input :language_other, label: t('activerecord.attributes.user.language_other')

  = f.fields_for :user_info do |ui|
    = ui.input :birthday, as: :string, label: t('activerecord.attributes.user_info.birthday'),
            placeholder: t('activerecord.attributes.user_info.birthday'),
            input_html: { 'data-provide': 'datepicker',
                    'data-date-format': 'dd.mm.yyyy',
                    'data-date-language': 'de',
                    'data-date-autoclose': true }
    = ui.input :occupation, placeholder: t('activerecord.attributes.user_info.occupation'),
            label: t('activerecord.attributes.user_info.occupation')
    = ui.input :reference_to_diabetes, as: :check_boxes, collection: reference_to_diabetes_list,
            label: t('activerecord.attributes.user_info.reference_to_diabetes'),
            checked: f.object.user_info.reload.attributes['reference_to_diabetes']
  hr.mb-4
  h3 = t('activerecord.attributes.user.help_services')
  = f.fields_for :help_service_assignments, @help_service_assignments do |hsa|
    = hsa.input :help_service_id, as: :hidden
    = hsa.input :assignee_type, as: :hidden
    = hsa.input :assignee_id, as: :boolean, label: hsa.object.help_service_description,
            input_html: { checked: !hsa.object.new_record? }
  hr.mb-4
  h3 = t('activerecord.attributes.user.care_ages')
  = f.fields_for :care_ages_users, @care_ages_users do |ca|
    = ca.input :id, as: :hidden
    = ca.input :care_age_id, as: :hidden
    = ca.input :user_id, as: :boolean, label: ca.object.care_age_description,
            input_html: { checked: !ca.object.new_record? }

  h3 = 'Kontaktdaten'
  hr.mb-4
  = f.fields_for :address do |a|
    = a.input :phone_private, placeholder: t('activerecord.attributes.address.phone_private'),
                              label: t('activerecord.attributes.address.phone_private')
    = a.input :phone_mobile, placeholder: t('activerecord.attributes.address.phone_mobile'),
                             label: t('activerecord.attributes.address.phone_mobile')
    = a.input :phone_business, placeholder: t('activerecord.attributes.address.phone_business'),
                               label: t('activerecord.attributes.address.phone_business')
    = a.input :email_business, placeholder: t('activerecord.attributes.address.email_business'),
                               label: t('activerecord.attributes.address.email_business')
  h3 = 'Kontoinformationen'
  hr.mb-4
  = f.fields_for :bank_account do |b|
    = b.hidden_field :id, value: b.object.id
    = b.input :account_holder, placeholder: t('activerecord.attributes.bank_account.account_holder'),
              label: t('activerecord.attributes.bank_account.account_holder')
    = b.input :iban, placeholder: t('activerecord.attributes.bank_account.iban'),
              label: t('activerecord.attributes.bank_account.iban')
    = b.input :bic, placeholder: t('activerecord.attributes.bank_account.bic'),
              label: t('activerecord.attributes.bank_account.bic')
  hr.mb-4
    = f.submit t('send'), class: 'btn btn-danger btn-lg mb-4'

app/views/admin/users/_form.slim
= simple_form_for(@form, url: admin_users_path, defaults: { input_html: { class: 'form-inline' } }) do |f|
  h3 = 'Adress-Informationen'
  hr.mb-4
    = f.input :address_salutation, placeholder: t('activerecord.attributes.address.salutation'),
              label: t('activerecord.attributes.address.salutation'), required: true
    = f.input :address_first_name, placeholder: t('activerecord.attributes.address.first_name'),
              label: t('activerecord.attributes.address.first_name')
    = f.input :address_last_name, placeholder: t('activerecord.attributes.address.last_name'),
              label: t('activerecord.attributes.address.last_name')
    = f.input :address_street, placeholder: t('activerecord.attributes.address.street'),
              label: t('activerecord.attributes.address.street')
    = f.input :address_zip, placeholder: t('activerecord.attributes.address.zip'),
              label: t('activerecord.attributes.address.zip')
    = f.input :address_city, placeholder: t('activerecord.attributes.address.city'),
              label: t('activerecord.attributes.address.city')
  h3 = 'Benutzer-Informationen'
  hr.mb-4
  = f.input :user_email, as: :email, placeholder: t('activerecord.attributes.user.email'),
            label: t('activerecord.attributes.user.email'), required: true
  = f.input :user_role, collection: UsersHelper.roles, label: t('activerecord.attributes.user.role'),
            input_html: { class: 'custom-select' }
  = f.hidden_field :user_password, value: @nr
  = f.hidden_field :user_password_confirmation, value: @nr
  .other_language
  = f.input :user_language, label: false, collection: user_languages_list,
            input_html: { class: 'custom-select' }
  = f.input :user_language_other, label: t('activerecord.attributes.user.language_other')
  = f.input :user_info_birthday, as: :string, label: t('activerecord.attributes.user_info.birthday'),
            placeholder: t('activerecord.attributes.user_info.birthday'),
            input_html: { 'data-provide': 'datepicker',
                          'data-date-format': 'dd.mm.yyyy',
                          'data-date-language': 'de',
                          'data-date-autoclose': true }
  = f.input :user_info_occupation, placeholder: t('activerecord.attributes.user_info.occupation'),
            label: t('activerecord.attributes.user_info.occupation')
  = f.input :user_info_reference_to_diabetes, as: :check_boxes,
            collection: reference_to_diabetes_list, label: t('activerecord.attributes.user_info.reference_to_diabetes')
  hr.mb-4
  h3 = t('activerecord.attributes.user.help_services')
  - if f.object.errors.messages[:help_service_assignment].present?
    = f.error_notification message: f.object.errors.messages[:help_service_assignment].to_sentence
  = f.fields_for :help_service_assignments do |hsa|
    = hsa.input :help_service_id, as: :hidden
    = hsa.input :assignee_type, as: :hidden
    = hsa.input :assignee_id, as: :boolean, label: hsa.object.help_service_description
  hr.mb-4
  h3 = 'Betreuungsalter'
  - if f.object.errors.messages[:care_ages_users].present?
    = f.error_notification message: f.object.errors.messages[:care_ages_users].to_sentence
  = f.fields_for :care_ages_users do |ca|
    = ca.input :care_age_id, as: :hidden
    = ca.input :user_id, as: :boolean, label: ca.object.care_age_description
  h3 = 'Kontaktdaten'
  hr.mb-4
  = f.input :address_phone_private, placeholder: t('activerecord.attributes.address.phone_private'),
            label: t('activerecord.attributes.address.phone_private')
  = f.input :address_phone_mobile, placeholder: t('activerecord.attributes.address.phone_mobile'),
            label: t('activerecord.attributes.address.phone_mobile')
  = f.input :address_phone_business, placeholder: t('activerecord.attributes.address.phone_business'),
            label: t('activerecord.attributes.address.phone_business')
  = f.input :address_email_business, placeholder: t('activerecord.attributes.address.email_business'),
            label: t('activerecord.attributes.address.email_business')
  h3 = 'Kontoinformationen'
  hr.mb-4
  = f.input :bank_account_account_holder, placeholder: t('activerecord.attributes.bank_account.account_holder'),
                                          label: t('activerecord.attributes.bank_account.account_holder')
  = f.input :bank_account_iban, placeholder: t('activerecord.attributes.bank_account.iban'),
                                label: t('activerecord.attributes.bank_account.iban')
  = f.input :bank_account_bic, placeholder: t('activerecord.attributes.bank_account.bic'),
                               label: t('activerecord.attributes.bank_account.bic')
  hr.mb-4
    = f.submit t('send'), class: 'btn btn-danger btn-lg mb-4'

app/views/admin/users/_users_grid.slim
== grid(@users_grid, show_filters: :no, hide_csv_button: true, upper_pagination_panel: false) do |g|
  - g.action_column html_check_box: true
  - g.blank_slate do
    - 'Keine Fälle gefunden.'
  - g.column name: 'Nachname', filter: false, assoc: %i[address], attribute: 'last_name' do |user|
    - [user.address_last_name&.capitalize, { style: 'column-width:200px;' }]
  - g.column name: 'Vorname', filter: false, assoc: %i[address], attribute: 'first_name' do |user|
    - [user.address_first_name&.capitalize, { style: 'column-width:200px;' }]
  - g.column name: 'PLZ', filter: false, assoc: %i[address], attribute: 'zip' do |user|
    - [user.address_zip, { style: 'column-width:100px;' }]
  - g.column name: 'Tel. mobil', filter: false, assoc: %i[address], attribute: 'phone_mobile' do |user|
    - [user.address&.phone_mobile, { style: 'column-width:150px;' }]
  - g.column name: 'E-Mail', attribute: 'email' do |user|
    - [user.email, { style: 'column-width:300px;' }]
  - g.column name: 'Sprache(n)', attribute: 'language' do |user|
    - [user.languages, { style: 'column-width:80px;' }]
  - g.column name: 'Rolle', attribute: 'role' do |user|
    - [user.role&.capitalize, { style: 'column-width:50px;' }]
  - g.column name: 'Anfrage', filter: false, in_csv: false do |user|
    - (link_to 'Anzeigen', admin_user_path(user), class: 'ml-2 btn-primary btn-sm') + \
      (link_to 'Bearbeiten', edit_admin_user_path(user), class: 'ml-2 btn-primary btn-sm') + \
      (link_to 'Löschen', admin_user_path(user), method: :delete, class: 'ml-2 btn-danger btn-sm',
        id: "delete_#{user.id}", data: { confirm: t('.confirm_delete') })

app/views/admin/users/edit.slim
.row
  .col-sm-12
    = render '/admin/users/edit', form: @form

app/views/admin/users/index.slim
= form_with url: destroy_all_admin_users_path, html: { id: 'users_form_index' }, method: :post do
  .row[style='width: fit-content;']
    .d-flex.align-items-end.flex-column-reverse
      =render 'users_grid'
      p
        button.btn.btn-default[type="submit" data-confirm="#{t('.confirm_delete')}"] Ausgewählte Benutzer löschen
        = link_to 'Neuer Benutzer', new_admin_user_path, class: 'btn btn-primary'
        button.btn.btn-primary
              .wg-external-csv-export-button[data-grid-name="users"
                                             style="float: right;"] CSV exportieren

app/views/admin/users/new.slim
= render 'form', form: @form

app/views/admin/users/show.slim
.container
  .row
    .col-md-12.d-flex.justify-content-end
      = link_to t('admin.show.resend_confirmation_instructions'), resend_confirmation_instructions_admin_user_path(@user), class: 'btn btn-secondary my-2'
      = link_to t('admin.show.edit_user'), edit_admin_user_path(@user), class: 'btn btn-primary my-2'
      = link_to t('admin.show.delete_user'), admin_user_path(@user), class: 'btn btn-primary my-2', method: :delete

  .row
    .col-sm-12
      .card.mb-4
        .card-body
          h3.card-title = t 'admin.show.user_details'
          p.card-text
            table.table.table-head-noborder
              tbody
                tr
                  td style="width: 30rem" = t 'admin.show.salutations'
                  td = @user.address.salutation
                tr
                  td = t 'admin.show.name'
                  td = @user.full_name
                tr
                  td = t 'admin.show.address_street'
                  td = @user.address_street
                tr
                  td = t 'admin.show.address_zip'
                  td = @user.address_zip
                tr
                  td = t 'admin.show.address_city'
                  td = @user.address_city
                tr
                  td = t 'admin.show.location_address'
                  td = @user.location_address
                tr
                  td = t 'admin.show.birthday'
                  td = l(@user.user_info&.birthday)
                tr
                  td = t 'admin.show.occupation'
                  td = @user.user_info&.occupation
                tr
                  td = t 'admin.show.phone_private'
                  td = @user.phone_private
                tr
                  td = t 'admin.show.phone_mobile'
                  td = @user.phone_mobile
                tr
                  td = t 'admin.show.phone_business'
                  td = @user.phone_business
                tr
                  td = t 'admin.show.email_business'
                  td = @user.email_business
                tr
                  td = t 'admin.show.email'
                  td = @user.email
                tr
                  td = t 'admin.show.languages'
                  td = @user.languages
                tr
                  td = t 'admin.show.role'
                  td = @user.role&.capitalize
                tr
                  td = t 'admin.show.bank_account_account_holder'
                  td = @user.bank_account_account_holder
                tr
                  td = t 'admin.show.bank_account_bic'
                  td = @user.bank_account_bic
                tr
                  td = t 'admin.show.bank_account_iban'
                  td = @user.bank_account_iban
                tr
                  td = t 'admin.show.reference_to_diabetes'
                  td = reference_to_diabetes_text(@user.reference_to_diabetes)
                tr
                  td = t 'admin.show.language_other'
                  td = @user.language_other
                tr
                  td = t 'admin.show.reset_password_sent_at'
                  td = l @user.reset_password_sent_at, format: :short
                tr
                  td = t 'admin.show.created_at'
                  td = l @user.created_at, format: :short
                tr
                  td = t 'admin.show.updated_at'
                  td = l @user.updated_at, format: :short
                tr
                  td = t 'admin.show.confirmed_at'
                  td = l @user.confirmed_at, format: :short
                tr
                  td = t 'admin.show.confirmation_sent_at'
                  td = l @user.confirmation_sent_at, format: :short
                tr
                  td = t 'admin.show.care_ages'
                  td
                    ul[style="list-style-type:disc;"]
                      - @user.care_ages.each do |u|
                        li = u.description
                tr
                  td = t 'admin.show.help_services'
                  td
                    ul[style="list-style-type:disc;"]
                      - @user.help_services.each do |u|
                        li = u.description
                tr
                  td = t 'admin.show.cases'
                  td
                    ul[style="list-style-type:disc;"]
                    - @user.cases.each do |c|
                      li = link_to c.identifier, c