config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'high_voltage/pages#show', id: 'about'
  namespace :admin do
    resources :users do
      collection do
        post 'destroy_all', to: 'users#destroy_all', as: :destroy_all
      end
      member do
        get 'resend_confirmation_instructions', to: 'users#resend_confirmation_instructions',
                                                as: :resend_confirmation_instructions
      end
    end
  end
  devise_for :users, skip: [:registrations], controllers: { confirmations: 'confirmations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :cases, except: %i[destroy] do
    resources :search_nannies, only: :index
    put 'reject', to: 'cases/states#reject', as: :reject
    put 'discard', to: 'cases/states#discard', as: :discard
    put 'request_nanny/:user_id', to: 'cases/states#request_nanny', as: :request_nanny
    get 'show_nanny/:id', to: 'users#show', as: :show_nanny
    put 'accept', to: 'cases/states#accept', as: :accept
    put 'refuse', to: 'cases/states#refuse', as: :refuse
    put 'finish', to: 'cases/states#finish', as: :finish
    put 'complete', to: 'cases/states#complete', as: :complete
    put 'reset', to: 'cases/states#reset', as: :reset
    get 'pdf', to: 'cases/pdf#pdf', as: :pdf
    collection do
      get 'csv', to: 'cases#csv_export', as: :csv
    end
  end

  resources :users, except: %i[new create]
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert.fade.show role="alert" class="alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      .alert-icon
        i.flaticon-warning
      .alert-text
        = content_tag :div, msg, id: "flash_#{name}"
      .alert-close
        button.close aria-label="Close" data-dismiss="alert" type="button"
          span aria-hidden="true"
            i.la.la-close

- if @case&.errors&.any?
  .alert.fade.show role="alert" class="alert-danger"
    .alert-icon
      i.flaticon-warning
    .alert-text
      ul
        - @case.errors.full_messages.each do |error|
          li
            = error
    .alert-close
      button.close aria-label="Close" data-dismiss="alert" type="button"
        span aria-hidden="true"
          i.la.la-close

- if show_complete_profile_flash?(current_user)
  .alert.fade.show role="alert" class="alert-danger"
    .alert-icon
      i.flaticon-warning
    .alert-text
      = t('.complete_profile')
      = link_to t('.here'), edit_user_path(current_user)
    .alert-close
      button.close aria-label="Close" data-dismiss="alert" type="button"
        span aria-hidden="true"
          i.la.la-close

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 4.0
.container
  nav.navbar.navbar-expand-lg.navbar-light
    = link_to image_tag('logo.png', width: '100px'), root_path, class: 'navbar-brand'
    button.navbar-toggler { aria-controls='navbarSupportedContent' aria-expanded='false'
      data-target='#navbarSupportedContent' data-toggle='collapse' type='button' }
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        = render 'layouts/navigation_links'
      - if user_signed_in?
        = link_to t('.sign_out'), destroy_user_session_path, method: 'delete', class: 'nav-link'
      - else
        = link_to t('.sign_in'), new_user_session_path, class: 'nav-link'

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  - if current_user.admin?
    li.nav-item = link_to t('.dashboard'), cases_path, class: 'nav-link'
    li.nav-item.active = link_to t('.nanny_search'), '#', class: 'nav-link disabled completely-disabled'
    li.nav-item = link_to t('.admin'), admin_users_path, class: 'nav-link'
  - else
    li.nav-item = link_to t('.cases'), cases_path, class: 'nav-link'
    li.nav-item.active = link_to t('.documentation'), '#', class: 'nav-link disabled completely-disabled'
    li.nav-item = link_to t('.profile'), edit_user_path(current_user), class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title = content_for?(:title) ? yield(:title) : 'Dianino'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Dianino'}"
    == stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'https://www.stiftung-dianino.de/wp-content/themes/dianino/assets/dist/js/iframeResizer.contentWindow.min.js'

    == csrf_meta_tags
    == yield(:head_tags)
  body
    - unless content_for?(:hide_navigation)
      header
        == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield